### model
model_name_or_path: /data/nlp_share/Llama-3.2-1B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
use_rslora: true
use_dora: true
lora_dropout: 0.05
lora_rank: 8
lora_alpha: 16

### dataset
dataset: boolq_train_2
template: llama3
cutoff_len: 2048
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: custom/train/models/boolq/lora_1B_train2_seed1
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 3.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
seed: 1
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
